import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🔍 Testing products and their types...');

  // Get all products with their categories
  const products = await prisma.product.findMany({
    include: {
      category: true
    }
  });

  console.log(`Found ${products.length} products:`);
  
  products.forEach((product, index) => {
    console.log(`${index + 1}. ${product.name}`);
    console.log(`   Category: ${product.category?.name || 'No category'}`);
    console.log(`   Category ID: ${product.categoryId}`);
    console.log(`   Weight: ${product.weight}g`);
    console.log(`   Price: ${product.price}`);
    console.log('---');
  });

  // Check what types would be generated by the frontend logic
  console.log('\n📋 Frontend type mapping:');
  products.forEach((product, index) => {
    let type = 'Khác';
    if (product.name.includes('tinh chế')) type = 'Yến tinh chế';
    else if (product.name.includes('rút lông')) type = 'Yến rút lông';
    else if (product.name.includes('thô')) type = 'Tổ yến thô';
    
    console.log(`${index + 1}. ${product.name} -> Type: ${type}`);
  });
}

main()
  .catch((e) => {
    console.error('❌ Error testing products:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  }); 