import type { Metadata } from 'next';
import './fonts.css';
import './globals.css';
import { ResponsiveNavbar } from '@/components/ResponsiveNavbar';
import { Providers } from '@/components/Providers';
import { HydrationSafe } from '@/components/HydrationSafe';
import Footer from '@/components/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="font-sans">
      <body>
        <Providers>
          <HydrationSafe>
            <ResponsiveNavbar />
          </HydrationSafe>
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
