import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import "./globals.css";
import { ResponsiveNavbar } from "@/components/ResponsiveNavbar";
import { Providers } from "@/components/Providers";
import { HydrationSafe } from "@/components/HydrationSafe";
import Footer from "@/components/Footer";

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '700', '900'],
  style: ['normal', 'italic'],
  variable: '--font-inter',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} font-sans`}>
      <body>
        <Providers>
          <HydrationSafe>
            <ResponsiveNavbar />
          </HydrationSafe>
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
