import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { MainNavbar } from "@/components/MainNavbar";
import { Providers } from "@/components/Providers";
import { HydrationSafe } from "@/components/HydrationSafe";

const inter = localFont({
  src: [
    { path: "../public/fonts/Inter/Inter-Regular.woff2", weight: "400", style: "normal" },
    { path: "../public/fonts/Inter/Inter-Medium.woff2", weight: "500", style: "normal" },
    { path: "../public/fonts/Inter/Inter-SemiBold.woff2", weight: "600", style: "normal" },
    { path: "../public/fonts/Inter/Inter-Bold.woff2", weight: "700", style: "normal" },
  ],
  variable: "--font-primary",
  display: "swap",
});

const poppins = localFont({
  src: [
    { path: "../public/fonts/Poppins/Poppins-Regular.ttf", weight: "400", style: "normal" },
    { path: "../public/fonts/Poppins/Poppins-Medium.ttf", weight: "500", style: "normal" },
    { path: "../public/fonts/Poppins/Poppins-SemiBold.ttf", weight: "600", style: "normal" },
    { path: "../public/fonts/Poppins/Poppins-Bold.ttf", weight: "700", style: "normal" },
  ],
  variable: "--font-secondary",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${poppins.variable} font-sans antialiased`}>
        <Providers>
          <HydrationSafe>
            <MainNavbar />
          </HydrationSafe>
          {children}
        </Providers>
      </body>
    </html>
  );
}
