import { Product } from "@/components/ProductCard";

export const products: Product[] = [
  {
    id: "p1",
    name: "Premium Refined Birdnest 50g",
    image: "/images/p1.png",
    price: 2500000,
    description: "High quality, ready-to-cook refined birdnest from Kien Giang.",
    weight: 50,
    type: "Refined Nest",
    quantity: 12,
    sold: 3200,
    reviews: [
      { user: "Nguyen Van A", rating: 5, comment: "Sản phẩm rất chất lượng, đóng gói đẹp." },
      { user: "Tran Thi B", rating: 4, comment: "Yến ngon, giao hàng nhanh." }
    ]
  },
  {
    id: "p2",
    name: "Raw Birdnest 100g",
    image: "/images/p2.png",
    price: 4200000,
    description: "Raw, natural birdnest, carefully selected and packed.",
    weight: 100,
    type: "Raw Nest",
  },
  {
    id: "p3",
    name: "Feather-removed Birdnest 200g",
    image: "/images/p3.png",
    price: 7900000,
    description: "Feather-removed, premium birdnest for health and gifting.",
    weight: 200,
    type: "Feather-removed Nest",
  },
  {
    id: "p4",
    name: "Premium Refined Birdnest 100g",
    image: "/images/p1.png",
    price: 4800000,
    description: "Premium refined birdnest, 100g pack.",
    weight: 100,
    type: "Refined Nest",
  },
  {
    id: "p5",
    name: "Raw Birdnest 50g",
    image: "/images/p2.png",
    price: 2100000,
    description: "Raw birdnest, 50g pack.",
    weight: 50,
    type: "Raw Nest",
  },
  {
    id: "p6",
    name: "Feather-removed Birdnest 100g",
    image: "/images/p3.png",
    price: 3900000,
    description: "Feather-removed birdnest, 100g pack.",
    weight: 100,
    type: "Feather-removed Nest",
  },
  {
    id: "p7",
    name: "Premium Refined Birdnest 200g",
    image: "/images/p1.png",
    price: 9500000,
    description: "Premium refined birdnest, 200g pack.",
    weight: 200,
    type: "Refined Nest",
  },
  {
    id: "p8",
    name: "Raw Birdnest 200g",
    image: "/images/p2.png",
    price: 8200000,
    description: "Raw birdnest, 200g pack.",
    weight: 200,
    type: "Raw Nest",
  },
  {
    id: "p9",
    name: "Feather-removed Birdnest 50g",
    image: "/images/p3.png",
    price: 2100000,
    description: "Feather-removed birdnest, 50g pack.",
    weight: 50,
    type: "Feather-removed Nest",
  },
  // Combos (from homepage)
  {
    id: "c1",
    name: "Combo 1",
    image: "/images/p1.png",
    price: 6500000,
    description: "Combo yến cao cấp, tiết kiệm hơn.",
    weight: 150,
    type: "Combo",
  },
  {
    id: "c2",
    name: "Combo 2",
    image: "/images/p2.png",
    price: 7000000,
    description: "Combo yến đa dạng, phù hợp làm quà tặng.",
    weight: 200,
    type: "Combo",
  },
  // Homepage products
  {
    id: "h1",
    name: "Yến tinh chế Khánh Hòa",
    price: 3500000,
    image: "/images/p1.png",
    weight: 50,
    description: "Yến tinh chế chất lượng cao từ Khánh Hòa.",
    type: "Refined Nest",
  },
  {
    id: "h2",
    name: "Yến rút lông Nha Trang",
    price: 4000000,
    image: "/images/p2.png",
    weight: 100,
    description: "Yến rút lông tự nhiên, đóng gói tại Nha Trang.",
    type: "Raw Nest",
  },
  {
    id: "h3",
    name: "Tổ yến thô Bình Định",
    price: 3000000,
    image: "/images/p3.png",
    weight: 200,
    description: "Tổ yến thô nguyên chất từ Bình Định.",
    type: "Feather-removed Nest",
  },
]; 